### ISSUE TITLE
"timeout_order_test" _ASSERT_VALID_PRIO falied

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#1647]
**_Reported by Sharron LIU:_**

I added one "ztest_unit_test(clock_test)" right after "ztest_unit_test(timeout_order_test)", and I observe the latter failed with _ASSERT_VALID_PRIO.

See the test case here:
https://gerrit.zephyrproject.org/r/#/c/11216

To reproduce it
# source zephyr-env.sh
# cd tests/kernel/common
# add "CONFIG_ASSERT=y" to the "prj.conf"
# make qemu
# verify the assertion failure
```
ASSERTION FAIL [((priority) == 15 && _is_idle_thread(pEntry)) || (_is_prio_higher_or_equal((priority), (15 - 1)) && _is_prio_lower_or_equal((priority), ((-16))))] @ /home/sharron/workspace/views/iot/zephyr/arch/x86/core/thread.c:235:
	invalid priority (530); allowed range: 14 to -16
```

(Imported from Jira ZEP-1799)

**Comment by nashif** [comment]
**_by Sharron LIU:_**

I narrowed down the problem. I found the assertion raised only when I enabled two tests (see "tests/kernel/common/main.c" from the patch)
                         ztest_unit_test(timeout_order_test),
                         ztest_unit_test(clock_test)

To further narrow down the problem, I blank out the "clock_test". That is, in "tests/kernel/common/clock.c", commented out all tests, I still observe the failure.
```
void clock_test(void)
{
	//tclock_uptime();
	//tclock_cycle();
}
```

Interesting is, any additional ztest following "timeout_order_test" would leads to such an assertion failure.
So I think the failure comes from "timeout_order_test". I further narrowed down the problem. I originally suspected this related to poll calls, but this was quickly ruled out. Then try comment out this line, the assertion failure *disappeared*!
```
void timeout_order_test(void)
{
        /* drop prio to get all poll events together */
        //k_thread_priority_set(k_current_get(), prio + 1);                    <<< comment out this line
        k_sleep(2000);                        <<< using k_sleep() to relinquish CPU, instead
}
```

**Comment by nashif** [comment]
**_by Sharron LIU:_**

Additional info captured by GDB, when the assertion failure happen:
```
(gdb) b arch/x86/core/thread.c:235
Breakpoint 1 at 0x1032d7: file /home/sharron/workspace/views/iot/zephyr/arch/x86/core/thread.c, line 235.
(gdb) condition 1 priority>16
(gdb) c
Continuing.

Breakpoint 1, _new_thread (pStackMem=0x0, stackSize=0, pEntry=0x0,
    parameter1=0x0, parameter2=0x1098c0 <_idle_stack>,
    parameter3=0x108138 <thread_stack>, priority=530, options=530)
    at /home/sharron/workspace/views/iot/zephyr/arch/x86/core/thread.c:235
235             _ASSERT_VALID_PRIO(priority, pEntry);
(gdb) bt
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames:
#0  _new_thread (pStackMem=0x0, stackSize=0, pEntry=0x0, parameter1=0x0,
    parameter2=0x1098c0 <_idle_stack>, parameter3=0x108138 <thread_stack>,
    priority=530, options=530)
    at /home/sharron/workspace/views/iot/zephyr/arch/x86/core/thread.c:235
#1  0x00104a41 in k_thread_spawn (stack=0x0, stack_size=0, entry=0x0, p1=0x0,
    p2=0x1098c0 <_idle_stack>, p3=0x108138 <thread_stack>, prio=530,
    options=530, delay=1081656)
    at /home/sharron/workspace/views/iot/zephyr/kernel/thread.c:246
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

The GDB info tells an unexpected priority (530, sometimes it goes to 534) passed when someone try to create an thread. The thread entry function and stack size passed were also suspicious, they were both 0.

Maybe you could review the "timeout_order_test" and check what caused such an unexpected thread creation. Thanks.

**Comment by nashif** [comment]
**_by Benjamin Walsh:_**

It's as-if there is some stack corruption going on. _new_thread() has finished running when you hit k_thread_priority_set(), so it should have no impact on it.

**Comment by nashif** [comment]
**_by Sharron LIU:_**

_Benjamin Walsh_ , in the test case k_thread_priority_set() was invoked to decrease the priority of current thread. This triggers a context switch to the other three threads previously spawn. Later switch back when the three threads done.
Will such a context switch be the cause of stack corruption?

Observed @quark_se platform also.

**Comment by nashif** [comment]
**_by Benjamin Walsh:_**

_Sharron LIU_  It should not of course. What I don't understand from your stack trace is that it seems that the stack corruption happens when calling _new_thread(). However, that is done as part of the k_thread_spawn() call, and all three of them should have finished running before calling k_thread_priority_set() on the main thread, so I don't know where these calls to _new_thread() come from.

I'll try to trace through the code tonight.

**Comment by nashif** [comment]
**_by Benjamin Walsh:_**

There is an expectation from the test harness that the thread spawned is still of higher priority than the test suite thread when the test finishes and gives the semaphore. If that is not true anymore, the stack of the test is reused for the next test while the test is still in the kernel ready queue, causing corruption.

**Comment by nashif** [comment]
**_by Sharron LIU:_**

Verify assertion failure fixed. Closing this. Thanks.
