### ISSUE TITLE
windows build failed "AttributeError: 'module' object has no attribute 'iter_unpack'"

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#1653]
**_Reported by Sharron LIU:_**

Windows build "zephyr/tests/kernel/common" @quark_se_c1000_ss_devboard with ISSM/gcc-arc, failed.
```
  IRQ     isr_tables.c
Traceback (most recent call last):
  File "c:/zephyr/zephyr/arch/common/gen_isr_tables.py", line 191, in <module>
    main()
  File "c:/zephyr/zephyr/arch/common/gen_isr_tables.py", line 150, in main
    intlist = read_intlist(args.intlist)
  File "c:/zephyr/zephyr/arch/common/gen_isr_tables.py", line 82, in read_intlist
    struct.iter_unpack(intlist_entry_fmt, intdata)]
AttributeError: 'module' object has no attribute 'iter_unpack'
make[2]: *** [isr_tables.c] Error 1
make[2]: Leaving directory `/c/zephyr/zephyr/tests/kernel/common/outdir/quark_se_c1000_ss_devboard'
```

how-to-reproduce: from windows/mingw
# source zephyr-env.sh
# export ZEPHYR_GCC_VARIANT=issm
# cd tests/kernel/common
# make pristine;make BOARD=quark_se_c1000_ss_devboard
# verify build failed

Please review if it's Zephyr issue or ISSM toolchain issue. Thanks.

(Imported from Jira ZEP-1805)

**Comment by nashif** [comment]
**_by Andrew Boie:_**

I think you need to upgrade your Python.
struct.iter_unpack was added in Python 3.4.
https://www.python.org/downloads/windows/

**Comment by nashif** [comment]
**_by Sharron LIU:_**

will try python3.4

**Comment by nashif** [comment]
**_by Sharron LIU:_**

Issue not observed with Python 3.6
Closing this. Thanks.
