### ISSUE TITLE
samples/subsys/console breaks xtensa build

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#1836]
**_Reported by Andrew Boie:_**

```
apboie@wintermute:/projects/zephyr3/tests/ztest/include mmu /projects/zephyr3
$ sanitycheck -in 
Generating LALR tables
Platform 'arduino_101_mcuboot' not specified in any arch .ini file and will not be tested
Selecting default platforms per test case
Building testcase defconfigs...
63 tests selected, 13603 tests discarded due to filters
total complete:   13/  63  20%  failed:    0

xt-sim                    samples/subsys/console/getchar/test                FAILED: build_error
--------------../../../sanity-out/xt-sim/samples/subsys/console/getchar/test/build.log--------------
make[1]: Entering directory '/projects/zephyr3/samples/subsys/console/getchar'
make[2]: Entering directory '/projects/zephyr3'
make[3]: Entering directory '/projects/zephyr3/sanity-out/xt-sim/samples/subsys/console/getchar/test'
  Using /projects/zephyr3 as source for kernel
  GEN     ./Makefile
  CHK     include/generated/version.h
  CHK     misc/generated/configs.c
  CHK     include/generated/generated_dts_board.h
  CHK     include/generated/offsets.h
xt-xcc WARNING:  -nostartfiles is ignored
xt-xcc WARNING:  -nodefaultlibs is ignored
subsys/built-in.o: In function `console_getchar_init':
/projects/zephyr3/subsys/console/getchar.c:53: undefined reference to `uart_console_in_debug_hook_install'
/projects/zephyr3/subsys/console/getchar.c:55: undefined reference to `uart_register_input'
/projects/zephyr3/Makefile:857: recipe for target 'zephyr_prebuilt.elf' failed
make[3]: *** [zephyr_prebuilt.elf] Error 2
make[3]: Target 'all' not remade because of errors.
make[3]: Leaving directory '/projects/zephyr3/sanity-out/xt-sim/samples/subsys/console/getchar/test'
Makefile:177: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
make[2]: Target 'all' not remade because of errors.
make[2]: Leaving directory '/projects/zephyr3'
/projects/zephyr3/Makefile.inc:82: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/projects/zephyr3/samples/subsys/console/getchar'
--------------../../../sanity-out/xt-sim/samples/subsys/console/getchar/test/build.log--------------

total complete:   14/  63  22%  failed:    1

xt-sim                    samples/subsys/console/getline/test                FAILED: build_error
--------------../../../sanity-out/xt-sim/samples/subsys/console/getline/test/build.log--------------
make[1]: Entering directory '/projects/zephyr3/samples/subsys/console/getline'
make[2]: Entering directory '/projects/zephyr3'
make[3]: Entering directory '/projects/zephyr3/sanity-out/xt-sim/samples/subsys/console/getline/test'
  Using /projects/zephyr3 as source for kernel
  GEN     ./Makefile
  CHK     include/generated/version.h
  CHK     misc/generated/configs.c
  CHK     include/generated/generated_dts_board.h
  CHK     include/generated/offsets.h
xt-xcc WARNING:  -nostartfiles is ignored
xt-xcc WARNING:  -nodefaultlibs is ignored
subsys/built-in.o: In function `console_getline_init':
/projects/zephyr3/subsys/console/getline.c:45: undefined reference to `uart_register_input'
/projects/zephyr3/Makefile:857: recipe for target 'zephyr_prebuilt.elf' failed
make[3]: *** [zephyr_prebuilt.elf] Error 2
make[3]: Target 'all' not remade because of errors.
make[3]: Leaving directory '/projects/zephyr3/sanity-out/xt-sim/samples/subsys/console/getline/test'
Makefile:177: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
make[2]: Target 'all' not remade because of errors.
make[2]: Leaving directory '/projects/zephyr3'
/projects/zephyr3/Makefile.inc:82: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/projects/zephyr3/samples/subsys/console/getline'
--------------../../../sanity-out/xt-sim/samples/subsys/console/getline/test/build.log--------------

total complete:   15/  63  23%  failed:    2^CTraceback (most recent call last):
  File "/projects/zephyr3/scripts/sanitycheck", line 1936, in <module>
    main()
  File "/projects/zephyr3/scripts/sanitycheck", line 1871, in main
    args.extra_args, args.ccache)
  File "/projects/zephyr3/scripts/sanitycheck", line 1493, in execute
    self.goals = mg.execute(cb, cb_context)
  File "/projects/zephyr3/scripts/sanitycheck", line 840, in execute
    for line in iter(p.stderr.readline, b''):
KeyboardInterrupt
```

(Imported from Jira ZEP-1995)

**Comment by nashif** [comment]
**_by Andrew Boie:_**

Fixed by this commit, which ensures that the target can select CONFIG_UART_CONSOLE

```
commit 259949d10ede6fa07dd3c5e83f89aee54802b933
Refs: v1.7.99-909-g259949d
Author:     Anas Nashif <anas.nashif@intel.com>
AuthorDate: Mon Apr 10 19:53:23 2017 -0400
Commit:     Anas Nashif <nashif@linux.intel.com>
CommitDate: Tue Apr 11 03:14:26 2017 +0000

    samples: console: fixed filter and add CONFIG_

    The filter expects CONFIG_, otherwise it is noop

    Change-Id: I2b0a02b6450287a090b69a12324fe7f7cf494999
    Signed-off-by: Anas Nashif <anas.nashif@intel.com>
```
