### ISSUE TITLE
scripts/filter-known-issues.py does not work with python3

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#2125]
**_Reported by Anas Nashif:_**

```
ERROR: E: .known-issues/make.conf: can't load config file: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "./scripts/filter-known-issues.py", line 96, in config_import_path
    config_import_file(filename)
  File "./scripts/filter-known-issues.py", line 62, in config_import_file
    for m in re.finditer(config_regex, mm, re.MULTILINE):
  File "/usr/lib64/python3.5/re.py", line 220, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/filter-known-issues.py", line 145, in <module>
    config_import(args.config_dir)
  File "./scripts/filter-known-issues.py", line 118, in config_import
    config_import_path(path)
  File "./scripts/filter-known-issues.py", line 99, in config_import_path
    e, traceback.format_exc()))
Exception: E: .known-issues/: can't load config files: cannot use a string pattern on a bytes-like object Traceback (most recent call last):
  File "./scripts/filter-known-issues.py", line 96, in config_import_path
    config_import_file(filename)
  File "./scripts/filter-known-issues.py", line 62, in config_import_file
    for m in re.finditer(config_regex, mm, re.MULTILINE):
  File "/usr/lib64/python3.5/re.py", line 220, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: cannot use a string pattern on a bytes-like object
```

(Imported from Jira ZEP-2290)

**Comment by nashif** [comment]
**_by Paul Sokolovsky:_**

I'd say this misses info how to reproduce it (e.g. command line). Due to this, it's hard to decide whether https://github.com/zephyrproject-rtos/zephyr/pull/646 is good fix or has some issue (e.g overfixes something).
