### ISSUE TITLE
Testcase failure :tests/bluetooth/shell/testcase.ini#test_br 

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#2150]
**_Reported by rahul kumar:_**

[Testcase]:-->tests/bluetooth/shell/testcase.ini#test_br

Below is the Reference  Error Report for the mentioned Testcase.

```

 tests/bluetooth/shell/testcase.ini#test_br @  COMPLETION failed  type:qemu-zephyr-arm


Detailed description
====================
Automated test run failed.

Output (the target might have produced none; GDB will be needed at this point):

         @local               configure passed  type:qemu-zephyr-arm
build output: #
build output: # configuration written to .config
build output: #
build output: src/../../../../samples/bluetooth/gatt/.gap.o.cmd:3: warning: NUL character seen; rest of line ignored
build output: src/../../../../samples/bluetooth/gatt/.gap.o.cmd:4: warning: NUL character seen; rest of line ignored
build output: src/../../../../samples/bluetooth/gatt/.gap.o.cmd:5: *** missing separator.  Stop.
build output: make[3]: *** [zephyr-app-dir] Error 2
build output: make[2]: *** [sub-make] Error 2
build output: make[1]: *** [all] Error 2
build failed trace: Traceback (most recent call last):
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 1470, in _decorated_fn
build failed trace:     r = fn(*args, **kwargs)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 3027, in _methods_call
build failed trace:     self._build_serial, self._build_parallel)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 2937, in __method_trampoline
build failed trace:     return (self.__method_trampoline_call(fname, fn, _type, targets), None)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch-v0.11-branch/.git//tc.py", line 2904, in __method_trampoline_call
build failed trace:     r = getattr(self, fname)(self, *targets)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py:1669|/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py:1577", line 2, in __tc_zephyr_sanity_c_build_50_for_target
        @local               build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 2503, in _build_50_for_target
        @local               build failed trace:     app.build(_app, self, _target, app_src)
        @local               build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//app.py", line 132, in build
        @local               build failed trace:     ab.build(testcase, target, app_src)
        @local               build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git/l/app_zephyr.py", line 197, in build
        @local               build failed trace:     'make %(make_j)s -C %(zephyr_srcdir)s '
        @local               build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git/l/tc.py", line 681, in shcmd_local
        @local               build failed trace:     reporter = self, logfile = logfile)
        @local               build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch-v0.11-branch/it//tc.py", line 3110, in _shcmd_local
        @local               build failed trace:     { output_tag: logf, "alevel": 0})
        @local               build failed trace: failed_e: (u'exit code 2 from \'make -j -C /home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/target.git/tests/bluetooth/shell EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170626-1346-119:j6dg BOARD=qemu_cortex_m3 ARCH=arm CONF_FILE="prj_br.conf" O=/tmp/.run-170626-1346-119-c7uFOp/yymp/outdir-yymp-j6dg-qemu_cortex_m3\' @/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git/p_zephyr.py:197', {'build output': <open file '<fdopen>', mode 'w+b' at 0x2b0428000930>, 'alevel': 0})
        @local               build failed  type:qemu-zephyr-arm
        @local               COMPLETION failed  type:qemu-zephyr-arm

```

(Imported from Jira ZEP-2316)

**Comment by nashif** [comment]
**_by Maureen Helm:_**

It's not clear to me what you're trying to do. Is this a log from your internal test framework? Can you please provide your build command and commit SHA?

**Comment by nashif** [comment]
**_by Anas Nashif:_**

_rahul kumar_  Please reproduce this issue outside of the test framework you use. there is lots of noise in the log that you provide without any relation to the issue. Once you have reproduced this locally, provide the instructions of how you got the errors.

**Comment by nashif** [comment]
**_by rahul kumar:_**

Hi Anas,
Can you Elaborate what need to be added from my side ?

**Comment by nashif** [comment]
**_by Anas Nashif:_**

You need to document in the bug how to reproduce this in the zephyr tree and outside of your test environment.

**Comment by nashif** [comment]
**_by Mark Linkmeyer:_**

Inaky to investigate and assign appropriately.

**Comment by nashif** [comment]
**_by Inaky Perez-Gonzalez:_**

https://github.com/zephyrproject-rtos/zephyr/pull/821

**Comment by nashif** [comment]
**_by Chandrakala Kempanna:_**

_rahul kumar_ Please Verify

**Comment by nashif** [comment]
**_by rahul kumar:_**

tested and Verified
