### ISSUE TITLE
Testcase failure :--tests/bluetooth/shell/testcase.ini#test

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#2151]
**_Reported by rahul kumar:_**

Below is Reference report for the Given testcase :-

[Testcase]-->tests/bluetooth/shell/testcase.ini#test

```

tests/bluetooth/shell/testcase.ini#test  COMPLETION failed  type:arduino101


Detailed description
====================
Automated test run failed.

Output (the target might have produced none; GDB will be needed at this point):

         @local             configure passed  type:arduino101
build output: Merging arduino_101.conf
build output: #
build output: # configuration written to .config
build output: #
build output: src/../../../../samples/bluetooth/gatt/.gap.o.cmd:3: warning: NUL character seen; rest of line ignored
build output: src/../../../../samples/bluetooth/gatt/.gap.o.cmd:4: warning: NUL character seen; rest of line ignored
build output: src/../../../../samples/bluetooth/gatt/.gap.o.cmd:5: *** missing separator.  Stop.
build output: make[3]: *** [zephyr-app-dir] Error 2
build output: make[2]: *** [sub-make] Error 2
build output: make[1]: *** [all] Error 2
build failed trace: Traceback (most recent call last):
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 1470, in _decorated_fn
build failed trace:     r = fn(*args, **kwargs)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git/fl/tc.py", line 3027, in _methods_call
build failed trace:     self._build_serial, self._build_parallel)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch-v0.11-branch/.git//tc.py", line 2937, in __method_trampoline
build failed trace:     return (self.__method_trampoline_call(fname, fn, _type, targets), None)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch-v0.11-branch/.git//tc.py", line 2904, in __method_trampoline_call
build failed trace:     r = getattr(self, fname)(self, *targets)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py:1669|/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git/.py:1577", line 2, in __tc_zephyr_sanity_c_build_50_for_target
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 2503, in _build_50_for_target
build failed trace:     app.build(_app, self, _target, app_src)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//app.py", line 132, in build
build failed trace:     ab.build(testcase, target, app_src)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch-v0.11-branch/git//app_zephyr.py", line 197, in build
build failed trace:     'make %(make_j)s -C %(zephyr_srcdir)s '
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git//tc.py", line 681, in shcmd_local
build failed trace:     reporter = self, logfile = logfile)
build failed trace:   File "/home/jenkins/workspace/zephyr-v1.8-branch-v0.11-branch/git/cfl/tc.py", line 3110, in _shcmd_local
build failed trace:     { output_tag: logf, "alevel": 0})
build failed trace: failed_e: (u'exit code 2 from \'make -j -C /home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/target.git/tests/bluetooth/shell EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=-170626-1346-119:u3j6 BOARD=arduino_101 ARCH=x86  O=/tmp/.run70626-1346-119-c7uFOp/s5ik/outdir-s5ik-u3j6-arduino_101\' @/home/jenkins/workspace/zephyr-v1.8-branch--v0.11-branch/.git/l/app_zephyr.py:197', {'build output': <open file '<fdopen>', mode 'w+b' at 0x2b042800ec00>, 'alevel': 0})
         @local             build failed  type:arduino101
         @local             COMPLETION failed  type:arduino101

```

(Imported from Jira ZEP-2317)

**Comment by nashif** [comment]
**_by Anas Nashif:_**

Please provide more details and include instructions how to reproduce this in the tree. We cant see what is going on based on your testcase environment.

**Comment by nashif** [comment]
**_by Mark Linkmeyer:_**

Inaky to investigate and reassign.

**Comment by nashif** [comment]
Duplicate of GH-2150
