### ISSUE TITLE
zephyr.git/tests/ztest/test/base/testcase.yaml#test_verbose_0 :Evalution failed

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#2417]
**_Reported by rahul kumar:_**

As per [WK-35.5]

Toolchain used as :*ZEPHYR_GCC_VARIANT=zephyr*

This Testcase failed which is cause due to zephyr. When I reproduce this testcase.i found their is failure at evalution failure.The cause of failure is pasted in below :

```
Detailed description
====================
Automated test run failed.

Output (the target might have produced none; GDB will be needed at this point):

         @local             will run on target group 'target=arc'
         @local             configure passed  type:arduino101
build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss; rm -f /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss/.config' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/.git//app_zephyr.py:134
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/ztest/test/base/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=-170831-1228-90:0aye BOARD=arduino_101_sss ARCH=arc CONF_FILE=prj_verbose_0.conf O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss initconfig' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/app_zephyr.py:176
build output: Using /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/arc/arduino_101_sss/arduino_101_sss_defconfig as base
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/include/test.config
build output: Merging prj_verbose_0.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss/arc_console.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run0831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss/boot_config.conf
build output: #
build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/ztest/test/base EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:0aye BOARD=arduino_101_sss ARCH=arc CONF_FILE=prj_verbose_0.conf O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr//app_zephyr.py:206
build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101; rm -f /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/un-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101/.config' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr//app_zephyr.py:134
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/booting/stub/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=-170831-1228-90:0aye BOARD=arduino_101 ARCH=x86  O=/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101 initconfig' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/app_zephyr.py:176
build output: Using /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/x86/arduino_101/arduino_101_defconfig as base
build output: Merging /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/include/test.config
build output: Merging prj.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101/arc_console.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101/boot_stub_config.conf
build output: #
build output: # configuration written to .config
build output: #
build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/booting/stub EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:0aye BOARD=arduino_101 ARCH=x86  O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git//app_zephyr.py:206
         @local             build passed  type:arduino101
deployed (try 1/4) set([(u'kernel-arc', u'/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss/zephyr.bin'), (u'kernel-x86', u'/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/un-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101/zephyr.bin')])
deploy (1 tries) passed
deploy passed  type:arduino101
Reset
eval failed: expected console output 'RunID: -170831-1228-90:0aye' from console 'a101-16:default' NOT FOUND after 60.2 s
eval failed trace: Traceback (most recent call last):
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git//tc.py", line 1478, in _decorated_fn
eval failed trace:     r = fn(*args, **kwargs)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2971, in _method_run
eval failed trace:     return self.__method_trampoline_call(fname, fn, _type, targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2927, in __method_trampoline_call
eval failed trace:     r = getattr(self, fname)(*targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/zephyr_sanity.py", line 606, in eval
eval failed trace:     console = target.rt.get("console", None))
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 995, in expect
eval failed trace:     self.testcase.expecter.run()
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/expecter.py", line 255, in run
eval failed trace:     r = f(*args)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr//ecter.py", line 407, in console_rx_eval
eval failed trace:     { 'target': target, "console output": of })
eval failed trace: failed_e: (u"expected console output 'RunID: -170831-1228-90:0aye' from console 'a101-16:default' NOT FOUND after 60.2 s", {'console output': <open file u'/home/jenkins/workspace/zephyr-master-.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/n-170831-1228-90-tKjlQW/auzy/eval-buffers-00-0/console-jfsotc03a101-16:auzy-default.log', mode 'a+' at 0x7f4f9855dae0>, 'target': <.tc.target_c object at 0x7f4f98494d10>})
evaluation failed  type:arduino101
clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101_sss' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:256
Lcyw1    @jfsotc03/a101-16/x86  clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/auzy/outdir-auzy-0aye-arduino_101' @/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr///app_zephyr.py:256
         @local             clean passed  type:arduino101
         @local             COMPLETION failed  type:arduino101
```

(Imported from Jira ZEP-2588)

**Comment by nashif** [comment]
**_by Mark Linkmeyer:_**

_Vikash Kumar_ , please assign accordingly.

**Comment by nashif** [comment]
**_by Vikash Kumar:_**

_rahul kumar_  : Please work on this and update your observation with latest build.

**Comment by nashif** [comment]
**_by rahul kumar:_**

Will be working internally
