### ISSUE TITLE
 zephyr.git/tests/net/mld/testcase.yaml#test  :evalution failed

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#2418]
**_Reported by rahul kumar:_**

This testcase failed is due to evalution failure.
This Testcase evalution getting failed on the Board such as ma:x86 ,arduino101:x86 and qemu-zephyr-x86.
As per [35.5]--testcase failure  report is pasted below :-

```
Automated test run failed.

Output (the target might have produced none; GDB will be needed at this point):

build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard; rm -f /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/.config' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git//app_zephyr.py:134
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_devboard ARCH=x86  O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard initconfig' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:176
build output: Using /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/x86/quark_se_c1000_devboard/quark_se_c1000_devboard_defconfig as base
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/include/test.config
build output: Merging prj.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/arc_target.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/boot_config.conf
build output: #
build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_devboard ARCH=x86  O=/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:206
rc  build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard; rm -f /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/.config' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/cf.git/app_zephyr.py:134
rc  build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/booting/stub/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_ss_devboard ARCH=arc  O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard initconfig' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:176
rc  build output: Using /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/arc/quark_se_c1000_ss_devboard/quark_se_c1000_ss_devboard_defconfig as base
rc  build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/include/test.config
rc  build output: Merging prj.conf
rc  build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/un170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/arc_target.conf
rc  build output: Merging /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/boot_stub_config.conf
rc  build output: #
rc  build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/booting/stub EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_ss_devboard ARCH=arc  O=/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git//app_zephyr.py:206
         @local                build passed  type:ma

console output: PASS - mld_setup.
console output: ===================================================================
console output: starting test - join_group
console output:
console output:     Assertion failed at /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld/src/main.c:208: join_group: Cannot join IPv6 multicast group (ret not equal to 0)
console output: FAIL - join_group.
console output: ===================================================================
console output: starting test - leave_group
console output: PASS - leave_group.
console output: ===================================================================
console output: starting test - catch_join_group
console output: PASS - catch_join_group.
console output: ===================================================================
console output: starting test - catch_leave_group
console output: PASS - catch_leave_group.
console output: ===================================================================
console output: starting test - verify_join_group
console output: PASS - verify_join_group.
console output: ===================================================================
console output: starting test - verify_leave_group
console output: PASS - verify_leave_group.
console output: ===================================================================
console output: starting test - catch_query
console output: PASS - catch_query.
console output: ===================================================================
console output: starting test - verify_send_report
console output: PASS - verify_send_report.
console output: ===================================================================
console output: starting test - test_allnodes
console output: PASS - test_allnodes.
console output: ===================================================================
console output: starting test - test_soli_node
console output: PASS - test_soli_node.
console output: ===================================================================
console output: ===================================================================
console output: RunID: 170831-1228-90:xacc
console output: PROJECT EXECUTION FAILED
eval failed trace: Traceback (most recent call last):
eval failed trace:   File "/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/.git/tc.py", line 1478, in _decorated_fn
eval failed trace:     r = fn(*args, **kwargs)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2971, in _method_run
eval failed trace:     return self.__method_trampoline_call(fname, fn, _type, targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2927, in __method_trampoline_call
eval failed trace:     r = getattr(self, fname)(*targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc_zephyr_sanity.py", line 606, in eval
eval failed trace:     console = target.rt.get("console", None))
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 995, in expect
eval failed trace:     self.testcase.expecter.run()
console output: PROJECT EXECUTION FAILED
eval failed trace: Traceback (most recent call last):
eval failed trace:   File "/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/.git/tc.py", line 1478, in _decorated_fn
eval failed trace:     r = fn(*args, **kwargs)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2971, in _method_run
eval failed trace:     return self.__method_trampoline_call(fname, fn, _type, targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2927, in __method_trampoline_call
eval failed trace:     r = getattr(self, fname)(*targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc_zephyr_sanity.py", line 606, in eval
eval failed trace:     console = target.rt.get("console", None))
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 995, in expect
eval failed trace:     self.testcase.expecter.run()
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/expecter.py", line 255, in run
eval failed trace:     r = f(*args)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/expecter.py", line 451, in console_rx_eval
eval failed trace:     { 'target': target, "console output": of })
eval failed trace: failed_e: (u'found expected (for failure) `PROJECT EXECUTION FAILED` in console `srrsotc02/qc1000-03:default` at 1.59s', {'console output': <open file u'/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/eval-buffers-00-0/console-srrsotc02qc1000-03:8q6g-default.log', mode 'a+' at 0x7f4f781aadb0>, 'target': <tc.target_c object at 0x7f4f3818c1d0>})
evaluation failed  type:ma
clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:256
rc  clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run1-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/app_zephyr.py:256
clean passed  type:ma
```

(Imported from Jira ZEP-2589)

**Comment by nashif** [comment]
**_by Inaky Perez-Gonzalez:_**

This is a failure that is consistently happening on our automation infrastructure, along with many others that have the same symptom, from the report:

```
console output:     Assertion failed at /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld/src/main.c:208: join_group: Cannot join IPv6 multicast group (ret not equal to 0)
```

the only difference with building it from scratch, are that automation builds as:

for clarity, 
- OBJDIR=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard
- ZEPHYR=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/

```
mkdir -p OBJDIR
rm -f OBJDIR/.config
make -j -C ZEPHYR/tests/net/mld/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_devboard ARCH=x86  O=OBJDIR/ initconfig
make -j -C ZEPHYR/tests/net/mld EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_devboard ARCH=x86  O=OBJDIR
```

and adding an extra config file:

```
CONFIG_BOOT_BANNER=y
CONFIG_BOOT_DELAY=1000
```

which means that this change to the config file:

```
--- failed/.config	2017-09-01 15:44:58.330957409 -0700
+++ passed/.config	2017-09-01 15:41:20.882870277 -0700
@@ -115,7 +115,7 @@
 #
 # CONFIG_KERNEL_DEBUG is not set
 CONFIG_BOOT_BANNER=y
-CONFIG_BOOT_DELAY=1000
+CONFIG_BOOT_DELAY=0
 CONFIG_BUILD_TIMESTAMP=y
 # CONFIG_INT_LATENCY_BENCHMARK is not set
 # CONFIG_EXECUTION_BENCHMARKING is not set
```

suddenly makes the code pass.

So this is an interaction between the boot code and the app threads?

This is probably related to https://github.com/zephyrproject-rtos/zephyr/issues/1280, which also is a weird failure that only happens when BOOT_DELAY is on. And so are many other issues reported which probably all can be tied to the same problem.

**Comment by nashif** [comment]
**_by Inaky Perez-Gonzalez:_**

More data.

_Fixed_ https://github.com/zephyrproject-rtos/zephyr/issues/1280 by applying:

```
diff --git a/kernel/init.c b/kernel/init.c
index 39b0f0c..0d12575 100644
--- a/kernel/init.c
+++ b/kernel/init.c
@@ -193,6 +193,11 @@ static void _main(void *unused1, void *unused2, void *unused3)
 	ARG_UNUSED(unused3);
 
 	_sys_device_do_config_level(_SYS_INIT_LEVEL_POST_KERNEL);
+	if (boot_delay > 0) {
+		printk("***** delaying boot " STRINGIFY(CONFIG_BOOT_DELAY)
+		       "ms (per build configuration) *****\n");
+		k_sleep(CONFIG_BOOT_DELAY);
+	}
 
 	/* Final init level before app starts */
 	_sys_device_do_config_level(_SYS_INIT_LEVEL_APPLICATION);
@@ -205,11 +210,6 @@ static void _main(void *unused1, void *unused2, void *unused3)
 	__do_init_array_aux();
 #endif
 
-	if (boot_delay > 0) {
-		printk("***** delaying boot " STRINGIFY(CONFIG_BOOT_DELAY)
-		       "ms (per build configuration) *****\n");
-		k_sleep(CONFIG_BOOT_DELAY);
-	}
 	PRINT_BOOT_BANNER();
 	_init_static_threads();
 
``` 

this passes Hello World and a few other random TCs I threw at it. Hoever, this testcase still fails on:

- QC10k/x86 and Arduino 101/x86: Assertion failed at /home/inaky/z/kernel.git/tests/net/mld/src/main.c:208: join_group: Cannot join IPv6 multicast group (ret not equal to 0)
- QEMU/x86: crash: 
 ```
***** CPU Page Fault (error code 0x00000000)
Supervisor thread read address 0x00000004
PDE: 0x025 Present Read-only User
PTE: 0x000 Non-present Read-only Supervisor
Current thread ID = 0x004054e0
Faulting segment:address = 0x0008:0x00008a74
eax: 0x00000000, ebx: 0x00000000, ecx: 0x00000000, edx: 0x00000000
esi: 0x00000246, edi: 0xffffffc2, ebp: 0x0040c418, esp: 0x0040c408
eflags: 0x2
Fatal fault in essential thread! Spinning...
Terminate emulator due to fatal kernel error
```
this is a crash on sys_dlist_remove(), which comes from:
```
(gdb) i s
#0  sys_dlist_remove (node=node@entry=0x0) at /home/inaky/z/kernel.git/include/misc/dlist.h:445
#1  0x00008df2 in sys_dlist_get (list=0x405470 <wait_data+16>) at /home/inaky/z/kernel.git/include/misc/dlist.h:466
#2  _handle_obj_poll_events (events=0x405470 <wait_data+16>, state=2) at /home/inaky/z/kernel.git/kernel/poll.c:315
#3  0x00009470 in handle_poll_events (sem=<optimized out>) at /home/inaky/z/kernel.git/kernel/sem.c:77
#4  do_sem_give (sem=0x405460 <wait_data>) at /home/inaky/z/kernel.git/kernel/sem.c:95
#5  k_sem_give (sem=0x405460 <wait_data>) at /home/inaky/z/kernel.git/kernel/sem.c:136
#6  0x000012a7 in tester_send (iface=0x405140 <__net_if_net_test_mld_0>, pkt=0x407b40 <_k_mem_slab_buf_tx_pkts+1216>) at /home/inaky/z/kernel.git/tests/net/mld/src/main.c:114
#7  0x0000390b in net_if_tx (iface=0x405140 <__net_if_net_test_mld_0>) at /home/inaky/z/kernel.git/subsys/net/ip/net_if.c:121
#8  0x000039ca in net_if_process_events (event=0x405440 <__net_if_event_net_test_mld_0>, ev_count=1) at /home/inaky/z/kernel.git/subsys/net/ip/net_if.c:185
#9  net_if_tx_thread (startup_sync=0x4050e0 <startup_sync>) at /home/inaky/z/kernel.git/subsys/net/ip/net_if.c:229
#10 0x00009788 in _thread_entry (entry=0x395c <net_if_tx_thread>, p1=0x4050e0 <startup_sync>, p2=0x0, p3=0x0) at /home/inaky/z/kernel.git/kernel/thread.c:186
#11 0x00000202 in ?? ()
```
