### ISSUE TITLE
zephyr.git/tests/net/mld/testcase.yaml#test :Evalution failed

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#2420]
**_Reported by rahul kumar:_**

This testcase failed at particular boards *ma:x86* ,*arduino101:x86*  ,*qemu-zephyr-x86* .
The Error report is pasted below :-

```

Automated test run failed.

Output (the target might have produced none; GDB will be needed at this point):

build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard; rm -f /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/.config' @/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/.git/app_zephyr.py:134
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=170831-1228-90:xacc BOARD=quark_se_c1000_devboard ARCH=x86  O=/home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard initconfig' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/.git//app_zephyr.py:176
build output: Using /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/x86/quark_se_c1000_devboard/quark_se_c1000_devboard_defconfig as base
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/include/test.config
build output: Merging prj.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/runi-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/arc_target.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/boot_config.conf
build output: #
build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=i-170831-1228-90:xacc BOARD=quark_se_c1000_devboard ARCH=x86  O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/.git/app_zephyr.py:206
build passed: 'mkdir -p /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard; rm -f /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/.config' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:134
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/booting/stub/ EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=-170831-1228-90:xacc BOARD=quark_se_c1000_ss_devboard ARCH=arc  O=/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/.run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard initconfig' @/home/jenkins/workspace/zephyr-master-.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git//app_zephyr.py:176
build output: Using /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/boards/arc/quark_se_c1000_ss_devboard/quark_se_c1000_ss_devboard_defconfig as base
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/include/test.config
build output: Merging prj.conf
build output: Merging /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/runi-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/arc_target.conf
build output: Merging /home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/un170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/boot_stub_config.conf
build output: #
build output: # configuration written to .config
build output: #
build passed: 'make -j -C /home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/booting/stub EXTRA_CFLAGS="-Werror -Wno-error=deprecated-declarations" KCPPFLAGS=-DTC_RUNID=-170831-1228-90:xacc BOARD=quark_se_c1000_ss_devboard ARCH=arc  O=/home/jenkins/workspace/zephyr-master-f-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/runi-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard' @/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/app_zephyr.py:206
         @local                build passed  type:ma
deployed (try 1/4) set([(u'kernel-arc', u'/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard/zephyr.bin'), (u'kernel-x86', u'/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/runi-170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard/zephyr.bin')])
deploy (1 tries) passed
deploy passed  type:ma
Reset
eval failed: found expected (for failure) `PROJECT EXECUTION FAILED` in console `srrsotc02/qc1000-03:default` at 1.59s
console output: ***** delaying boot 1000ms (per build configuration) *****
console output: ***** BOOTING ZEPHYR OS v1.9.0-rc2 (delayed boot 1000ms) - BUILD: Aug 31 2017 19:35:48 *****
console output: Running test suite net_mld_test
console output: ===================================================================
console output: starting test - mld_setup
console output: PASS - mld_setup.
console output: ===================================================================
console output: starting test - join_group
console output:
console output:     Assertion failed at /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/zephyr.git/tests/net/mld/src/main.c:208: join_group: Cannot join IPv6 multicast group (ret not equal to 0)
console output: FAIL - join_group.
console output: ===================================================================
console output: starting test - leave_group
console output: PASS - leave_group.
console output: ===================================================================
console output: starting test - catch_join_group
console output: PASS - catch_join_group.
console output: ===================================================================
console output: starting test - catch_leave_group
console output: PASS - catch_leave_group.
console output: ===================================================================
console output: starting test - verify_join_group
console output: PASS - verify_join_group.
console output: ===================================================================
console output: starting test - verify_leave_group
console output: PASS - verify_leave_group.
console output: ===================================================================
console output: starting test - catch_query
console output: PASS - catch_query.
console output: ===================================================================
console output: starting test - verify_send_report
console output: PASS - verify_send_report.
console output: ===================================================================

console output: ===================================================================
console output: RunID: 170831-1228-90:xacc
console output: PROJECT EXECUTION FAILED
eval failed trace: Traceback (most recent call last):
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 1478, in _decorated_fn
eval failed trace:     r = fn(*args, **kwargs)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2971, in _method_run
eval failed trace:     return self.__method_trampoline_call(fname, fn, _type, targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/tc.py", line 2927, in __method_trampoline_call
eval failed trace:     r = getattr(self, fname)(*targets)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/it/tc_zephyr_sanity.py", line 606, in eval
eval failed trace:     console = target.rt.get("console", None))
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/it/tc.py", line 995, in expect
eval failed trace:     self.testcase.expecter.run()
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/expecter.py", line 255, in run
eval failed trace:     r = f(*args)
eval failed trace:   File "/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/expecter.py", line 451, in console_rx_eval
eval failed trace:     { 'target': target, "console output": of })
eval failed trace: failed_e: (u'found expected (for failure) `PROJECT EXECUTION FAILED` in console `srrsotc02/qc1000-03:default` at 1.59s', {'console output': <open file u'/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/eval-buffers-00-0/console-srrsotc02qc1000-03:8q6g-default.log', mode 'a+' at 0x7f4f781aadb0>, 'target': <.tc.target_c object at 0x7f4f3818c1d0>})
aluation failed  type:ma
ean passed: 'rm -rf /home/jenkins/workspace/zephyr-master--v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/run170831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_devboard' @/home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/git/l/app_zephyr.py:256
 clean passed: 'rm -rf /home/jenkins/workspace/zephyr-master-v0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/tmp/un70831-1228-90-tKjlQW/8q6g/outdir-8q6g-xacc-quark_se_c1000_ss_devboard' @/home/jenkins/workspace/zephyr-master-0.11-branch/LABEL/verify/SHARD/1-3/ZEPHYR_GCC_VARIANT/zephyr/it/app_zephyr.py:256
clean passed  type:ma
COMPLETION failed  type:ma

```

(Imported from Jira ZEP-2591)

**Comment by nashif** [comment]
**_by Inaky Perez-Gonzalez:_**

Same results as ZEP-2589 (disabling boot_delay makes it pass).
