### ISSUE TITLE
Sanity Crashes with "FileNotFound" exception when running samples/static_lib/test

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#640]
**_Reported by Genaro Saucedo Tejada:_**

Steps to reproduce:

1 download: https://gerrit.zephyrproject.org/r/#/c/4142/1
2 run: run sanitycheck -vvv -T samples/static_lib --inline-logs

output:
```
qemu_x86                  samples/static_lib/test                            FAILED: build_error
-----------------------sanity-out/qemu_x86/samples/static_lib/test/build.log------------------------
Traceback (most recent call last):
  File "./scripts/sanitycheck", line 1797, in <module>
    main()
  File "./scripts/sanitycheck", line 1729, in main
    args.enable_slow, args.enable_asserts)
  File "./scripts/sanitycheck", line 1402, in execute
    self.goals = mg.execute(cb, cb_context)
  File "./scripts/sanitycheck", line 785, in execute
    callback_fn(context, self.goals, goal)
  File "./scripts/sanitycheck", line 1663, in chatty_test_cb
    log_info(goal.get_error_log())
  File "./scripts/sanitycheck", line 1618, in log_info
    with open(filename) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'sanity-out/qemu_x86/samples/static_lib/test/build.log'
```
This is the root cause of Jenkins voting +1 verify when full check is full of build errors:
https://gerrit.zephyrproject.org/r/#/c/4142/1
After crash it retries but there is no Success/failure Data and retries for 0 of 0 tests, automatically succeeding.

(Imported from Jira ZEP-723)

**Comment by nashif** [comment]
**_by Anas Nashif:_**

the mentioned patch is in review, it has some issues, no need to file bugs against changes that are not in the tree yet, just because it passed sanity does not mean anything else on top that fails should be seen as a bug

**Comment by nashif** [comment]
**_by Javier B Perez:_**

_Anas Nashif_  there is an issue in sanity as well, because sanity cannot find the file where to save the logs. not sure why.

**Comment by nashif** [comment]
**_by Andrew Boie:_**

it can't find the logs due to some goofiness in how that particular test is built (long story) but at any rate sanitycheck shouldn't explode like this.

**Comment by nashif** [comment]
**_by Andrew Boie:_**

https://gerrit.zephyrproject.org/r/#/c/9847/

**Comment by nashif** [comment]
**_by Sharron LIU:_**

Verified fixed when invoking
```
zephyr$ ./scripts/sanitycheck -vvv -T samples/static_lib/ --inline-logs
```
