### ISSUE TITLE
Enable USB CDC by default on Arduino 101 and redirect serial to USB

### ISSUE THREAD

**Issue by nashif** [zephyriot/zep-jira14#682]
**_Reported by Anas Nashif:_**

As a user of the Arduino 101, I want to use the one and only UART port for connecting additional devices and want the to use serial over USB CDC for system messages and console.

Enable USB CDC by default on the Arduino 101 and redirect console to that device

(Imported from Jira ZEP-775)

**Comment by nashif** [comment]
**_by Jithu Joseph:_**

With the addition of a hacked up uart_poll implementation (which is missing in the existing console API exposed by USB UART) , I am able to get  stuff partially working  using /dev/ttyACM0 USB UART as the stdout console. Partially as in :

1 Console output working
2. Console input mostly working . But , there are occasional  lockups (one such stack pasted below for reference), using the shell example  when I try stuff like  arrow keys / backspace etc.

Synchronization in UART API exposed by CDC ACM class  (or perhaps even usb controller driver  ) needs to be re looked .


<  hung backtrace  >
#0  uart_console_isr (unused=<optimized out>) at /home/jithu/code/zephyr/lf/crypto/heel/drivers/console/uart_console.c:322
#1  0x40014cc4 in cdc_acm_bulk_out (ep=3 '\003', ep_status=ep_status@entry=USB_DC_EP_DATA_OUT)
    at /home/jithu/code/zephyr/lf/crypto/heel/usb/class/cdc_acm.c:364
#2  0x40011d72 in usb_dw_isr_handler () at /home/jithu/code/zephyr/lf/crypto/heel/drivers/usb/device/usb_dc_dw.c:565
#3  0x40010ffe in usb_dw_isr_handler_irq10_stub ()
#4  0xa8008758 in main_task_stack ()
…

**Comment by nashif** [comment]
**_by Mark Linkmeyer:_**

_Jithu Joseph_ , what's the status on this? Is it on track to be implemented and merged before the 1.6 merge window closes on ww46.3?

**Comment by nashif** [comment]
**_by Jithu Joseph:_**

Since the USB UART doesn’t have a poll implementation,  it is not straightforward to hook it into zephyr's console framework (which needs both IRQ and poll implementation). 

So this is unlikely to be make it for 1.6

**Comment by nashif** [comment]
**_by Mark Linkmeyer:_**

_Anas Nashif_ , was this issue that Jithu mentions above before now?  Was it known when it was targeted for 1.6?  Is there a mitigation for this or must this be pushed out?

**Comment by nashif** [comment]
**_by Johan Hedberg:_**

Could the ISR lockup mentioned in the first comment be the same we recently fixed for Bluetooth UART? Patch currently in bluetooth branch:

commit bcb590e236ccab1eef2da962a873901704059c7d
Author: Carles Cufi <carles.cufi@nordicsemi.no>
Date:   Mon Oct 31 12:59:12 2016 +0100

    Bluetooth: uart: Fix UART TX stall condition

**Comment by nashif** [comment]
**_by Anas Nashif:_**

one way communication is better than nothing, we can always fix the input later, can you submit the code you have already?

**Comment by nashif** [comment]
**_by Jithu Joseph:_**

_Anas Nashif_  I will post the patch soon. You can take a call as to whether it is good to merge or not.

**Comment by nashif** [comment]
**_by Johan Hedberg:_**

Any update on uploading the patch for review? Merge window closes end of this week, so it'd be good to give it an opportunity for at least one review round if there's going to be any chance of getting this to 1.6.

**Comment by nashif** [comment]
**_by Jithu Joseph:_**

https://gerrit.zephyrproject.org/r/#/c/6596/

I havent defaulted to it since it doesnt work with  for inputs. It is left as a config option.

**Comment by nashif** [comment]
**_by Jithu Joseph:_**

Console output is merged , will open a new ticket to implement console input which is not working

**Comment by nashif** [comment]
**_by ethan gao:_**

I verified that it supports to redirect the x86 output to USB CDC ACM device, but it not works for ARC, so... here to confirm that Zephyr supports ARC output redirected to USB CDC ACM device in the next?

**Comment by nashif** [comment]
**_by ethan gao:_**

Verified that zephyr supports to redirect UART x86 output to USB CDC ACM device on Arduino_101 and quark_se_c1000, but no support to sensor subsystem and close it now
